### ISSUE TITLE
Project Shows Not Participating

### ISSUE THREAD

**Issue by Priyanshu-Aggarwal** [puruagarwal1/hacktoberfest-2022-dir#13]
![second](https://user-images.githubusercontent.com/72151968/193454397-fc658dc7-9373-4f35-9e79-fb7c10ab0685.JPG)

Please provide hacktoberfest topic in this repo OR  label hacktoberfest-accepted label in Pull Request/Merge Request.

**Comment by puruagarwal1** [comment]
Resolve the problems rather than adding new code.
